// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Murad.CQRS.WebApi.Data;

namespace Murad.CQRS.WebApi.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230207100942_add_data_student")]
    partial class add_data_student
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Murad.CQRS.WebApi.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Murad",
                            Surname = "Aliyev",
                            age = 21
                        },
                        new
                        {
                            Id = 2,
                            Name = "Osman",
                            Surname = "Bashirov",
                            age = 21
                        },
                        new
                        {
                            Id = 3,
                            Name = "Parviz",
                            Surname = "Yunisli",
                            age = 21
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
